### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by danieldjewell** [NCAR/pyngl#9]
Hi! 

Just curious -- there doesn't appear to be license information for PyNGL ... it looks like PyNIO is released under the Apache 2.0 license (https://github.com/NCAR/pynio/blob/master/LICENSE)? Would this be the same?

Thanks for the guidance!

**Comment by CAM-Gerlach** [comment]
Hey, could someone on the team please address this? Without a license, it is technically illegal for anyone to even to download and use PyNGL (all rights reserved is the default), nor contribute code to it and there could be serious legal liability down the road with contributed code if you accept community pull requests without ever defining a license (since you'll have to get written permission from everyone to chance the license, or else have to remove/replace their code).

**Comment by khallock** [comment]
Hi all, I'm sorry for the oversight regarding PyNGL's license. Yes, PyNGL is released under the same Apache 2.0 license as used by our other software, including NCL and PyNIO.

I have just updated the repository to include a [LICENSE](https://github.com/NCAR/pyngl/blob/develop/LICENSE) file. Thanks for bringing this to our attention!

**Comment by CAM-Gerlach** [comment]
Thanks @khallock !

**Comment by CAM-Gerlach** [comment]
I presume this issue should now be closed?
